-version: '3.8'
-
-service:
  - web:
     -build:
     -ports:
      - "8080:80"
     volumes:
      - .:/var/www/html
     depends_on:
      - db
      
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: littleones_db
      ports:
        - "3306:3306"
